# Generated by Django 3.2.23 on 2024-03-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='buy',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y')], default='other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
