# Generated by Django 3.2.23 on 2024-03-28 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_auto_20240327_1817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('name', 'owner')},
        ),
    ]
