# Generated by Django 3.2.23 on 2024-03-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together=set(),
        ),
    ]
