# Generated by Django 3.2.23 on 2024-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20240214_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_rxxwye', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='activity',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('hobbies', 'Hobbies'), ('sport', 'Sport'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=255, null=True),
        ),
    ]
